name: services

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  services:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: utf8mb4
        collation server: utf8mb4_general_ci
        mysql version: '8.0'
        mysql root password: seata-test
        mysql database: seata
        mysql user: seata
        mysql password: 123123
    - name: Setup Zookeeper
      run : |
       docker pull zookeeper:latest
       docker run --name zookeeper -d zookeeper:latest
