name: services

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  services:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    services:
      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181 
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: seata
          MYSQL_ROOT_HOST: 3306
        ports:
          - 3306:3306
    steps:
    - name: Setup MySQL
      run: echo 'mysql zk'
