# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: TCC dubbo e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: seata
          MYSQL_ROOT_HOST: 3306
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: git pull seata
#      run: |
#        cd /tmp
#        git clone -b develop https://github.com/seata/seata.git seata
#        cd seata
#        mvn clean package -DskipTests=true -Dcheckstyle.skip=true -U
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: test
      run: |
       nohup java -cp .:server/target/lib/*:server/target/seata-jit-server.jar io.seata.jit.server.Main &
       sleep 1m
       nohup java -cp .:tcc/target/lib/*:tcc/target/seata-jit-tcc.jar io.seata.jit.starter.TccProviderStarter &
       sleep 1m
       java -cp .:tcc/target/lib/*:tcc/target/seata-jit-tcc.jar io.seata.jit.starter.TccConsumerStarter
       ls ~/logs
    - name: Contains error.log
      run: bash -x ./check_error.sh
    - name: The job has failed
      if: failure()
      run: echo 'TCC model fail!'
